// <auto-generated />
using System;
using Curriculum.API.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Curriculum.API.Migrations
{
    [DbContext(typeof(CurriculumDbContext))]
    [Migration("20200925145544_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Curriculum.API.Data.Models.StudentCurriculum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StatusDescription")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50)
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.ToTable("StudentCurriculums");
                });

            modelBuilder.Entity("Curriculum.API.Data.Models.StudentCurriculum", b =>
                {
                    b.OwnsOne("Curriculum.API.Data.Models.Curriculum", "Curriculum", b1 =>
                        {
                            b1.Property<int>("StudentCurriculumId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                            b1.Property<int>("Capacity")
                                .HasColumnType("integer");

                            b1.Property<string>("EndTime")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .HasColumnType("integer");

                            b1.Property<bool>("IsCapacityCompleted")
                                .HasColumnType("boolean");

                            b1.Property<int>("RemainingCapacity")
                                .HasColumnType("integer");

                            b1.Property<int>("ReservedCapacity")
                                .HasColumnType("integer");

                            b1.Property<string>("StartTime")
                                .HasColumnType("text");

                            b1.HasKey("StudentCurriculumId");

                            b1.ToTable("StudentCurriculums");

                            b1.WithOwner()
                                .HasForeignKey("StudentCurriculumId");

                            b1.OwnsOne("Curriculum.API.Data.Models.Course", "Course", b2 =>
                                {
                                    b2.Property<int>("CurriculumStudentCurriculumId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer")
                                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                                    b2.Property<string>("Code")
                                        .HasColumnType("text");

                                    b2.Property<int>("Id")
                                        .HasColumnType("integer");

                                    b2.Property<int>("PracticalUnitCount")
                                        .HasColumnType("integer");

                                    b2.Property<int>("TheoryUnitCount")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Title")
                                        .HasColumnType("text");

                                    b2.Property<int>("Type")
                                        .HasColumnType("integer");

                                    b2.HasKey("CurriculumStudentCurriculumId");

                                    b2.ToTable("StudentCurriculums");

                                    b2.WithOwner()
                                        .HasForeignKey("CurriculumStudentCurriculumId");
                                });

                            b1.OwnsOne("Curriculum.API.Data.Models.Field", "Field", b2 =>
                                {
                                    b2.Property<int>("CurriculumStudentCurriculumId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer")
                                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                                    b2.Property<int>("DegreeType")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Id")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Title")
                                        .HasColumnType("text");

                                    b2.HasKey("CurriculumStudentCurriculumId");

                                    b2.ToTable("StudentCurriculums");

                                    b2.WithOwner()
                                        .HasForeignKey("CurriculumStudentCurriculumId");
                                });

                            b1.OwnsOne("Curriculum.API.Data.Models.Semester", "Semester", b2 =>
                                {
                                    b2.Property<int>("CurriculumStudentCurriculumId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer")
                                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                                    b2.Property<int>("Id")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Title")
                                        .HasColumnType("text");

                                    b2.Property<int>("Type")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Year")
                                        .HasColumnType("text");

                                    b2.HasKey("CurriculumStudentCurriculumId");

                                    b2.ToTable("StudentCurriculums");

                                    b2.WithOwner()
                                        .HasForeignKey("CurriculumStudentCurriculumId");
                                });

                            b1.OwnsOne("Curriculum.API.Data.Models.Teacher", "Teacher", b2 =>
                                {
                                    b2.Property<int>("CurriculumStudentCurriculumId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer")
                                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                                    b2.Property<string>("FullName")
                                        .HasColumnType("text");

                                    b2.Property<int>("Id")
                                        .HasColumnType("integer");

                                    b2.Property<string>("PersonnelId")
                                        .HasColumnType("text");

                                    b2.Property<string>("UserId")
                                        .HasColumnType("text");

                                    b2.HasKey("CurriculumStudentCurriculumId");

                                    b2.ToTable("StudentCurriculums");

                                    b2.WithOwner()
                                        .HasForeignKey("CurriculumStudentCurriculumId");
                                });
                        });

                    b.OwnsOne("Curriculum.API.Data.Models.Student", "Student", b1 =>
                        {
                            b1.Property<int>("StudentCurriculumId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                            b1.Property<string>("Code")
                                .HasColumnType("text");

                            b1.Property<DateTime>("CreateTime")
                                .HasColumnType("timestamp without time zone");

                            b1.Property<int>("Id")
                                .HasColumnType("integer");

                            b1.Property<string>("UserId")
                                .HasColumnType("text");

                            b1.HasKey("StudentCurriculumId");

                            b1.ToTable("StudentCurriculums");

                            b1.WithOwner()
                                .HasForeignKey("StudentCurriculumId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
