# https://github.com/elastic/logstash-docker
FROM logstash:7.9.1

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
RUN logstash-plugin install logstash-input-http