version: '3.4'

services:
  postgres:
    image: postgres:11.1
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
volumes:
  postgres: